live_config_reload = false

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 2
dynamic_padding = false
decorations = "Full"
opacity = 0.90
blur = false
startup_mode = "Maximized"
dynamic_title = true
option_as_alt = "Both"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 12.5

[selection]
save_to_clipboard = true

[colors.primary]
background = "#262335"
foreground = "#ffffff"

[colors.normal]
black   = "#262335"
red     = "#fe4450"
green   = "#72f1b8"
yellow  = "#f3e70f"
blue    = "#03edf9"
magenta = "#ff7edb"
cyan    = "#03edf9"
white   = "#ffffff"

[colors.bright]
black   = "#614d85"
red     = "#fe4450"
green   = "#72f1b8"
yellow  = "#fede5d"
blue    = "#03edf9"
magenta = "#ff7edb"
cyan    = "#03edf9"
white   = "#ffffff"
